#define	NURBANA_KEY_QUOTE_SINGLE_RIGHT	70
#define	NURBANA_KEY_COMA		83
#define	NURBANA_KEY_MINUS		28
#define	NURBANA_KEY_PERIOD		84
#define	NURBANA_KEY_SLASH		85
#define	NURBANA_KEY_0			27
#define	NURBANA_KEY_1			18
#define	NURBANA_KEY_2			19
#define	NURBANA_KEY_3			20
#define	NURBANA_KEY_4			21
#define	NURBANA_KEY_5			22
#define	NURBANA_KEY_6			23
#define	NURBANA_KEY_7			24
#define	NURBANA_KEY_8			25
#define	NURBANA_KEY_9			26
#define	NURBANA_KEY_SEMI_COLON		69
#define	NURBANA_KEY_EQUAL_SIGN		29
//#define	NURBANA_KEY_A			
//#define	NURBANA_KEY_B			
//#define	NURBANA_KEY_C			
//#define	NURBANA_KEY_D			
//#define	NURBANA_KEY_E			
//#define	NURBANA_KEY_F			
//#define	NURBANA_KEY_G			
//#define	NURBANA_KEY_H			
//#define	NURBANA_KEY_I			
//#define	NURBANA_KEY_J			
//#define	NURBANA_KEY_K			
//#define	NURBANA_KEY_L			
//#define	NURBANA_KEY_M			
//#define	NURBANA_KEY_N			
//#define	NURBANA_KEY_O			
//#define	NURBANA_KEY_P			
//#define	NURBANA_KEY_Q			
//#define	NURBANA_KEY_R			
//#define	NURBANA_KEY_S			
//#define	NURBANA_KEY_T			
//#define	NURBANA_KEY_U			
//#define	NURBANA_KEY_V			
//#define	NURBANA_KEY_W			
//#define	NURBANA_KEY_X			
//#define	NURBANA_KEY_Y			
//#define	NURBANA_KEY_Z			
#define	NURBANA_KEY_SQR_BRACKET_LEFT	49
#define	NURBANA_KEY_BACK_SLASH		51
#define	NURBANA_KEY_SQR_BRACKET_RIGHT	50
#define	NURBANA_KEY_QUOTE_SINGLE_LEFT	17
#define	NURBANA_KEY_a			60
#define	NURBANA_KEY_b			80
#define	NURBANA_KEY_c			78
#define	NURBANA_KEY_d			62
#define	NURBANA_KEY_e			41
#define	NURBANA_KEY_f			63
#define	NURBANA_KEY_g			64
#define	NURBANA_KEY_h			65
#define	NURBANA_KEY_i			46
#define	NURBANA_KEY_j			66
#define	NURBANA_KEY_k			67
#define	NURBANA_KEY_l			68
#define	NURBANA_KEY_m			82
#define	NURBANA_KEY_n			81
#define	NURBANA_KEY_o			47
#define	NURBANA_KEY_p			48
#define	NURBANA_KEY_q			39
#define	NURBANA_KEY_r			42
#define	NURBANA_KEY_s			61
#define	NURBANA_KEY_t			43
#define	NURBANA_KEY_u			45
#define	NURBANA_KEY_v			79
#define	NURBANA_KEY_w			40
#define	NURBANA_KEY_x			77
#define	NURBANA_KEY_y			44
#define	NURBANA_KEY_z			76
#define	NURBANA_KEY_BACKSPACE		30
#define	NURBANA_KEY_TAB			38
#define	NURBANA_KEY_ENTER		71
#define	NURBANA_KEY_PAUSE_BREAK		0
#define	NURBANA_KEY_SCROLL_LOCK		15
#define	NURBANA_KEY_ESC			1
#define	NURBANA_KEY_HOME		32
#define	NURBANA_KEY_LEFT_ARROW		97
#define	NURBANA_KEY_UP_ARROW		87
#define	NURBANA_KEY_RIGHT_ARROW		99
#define	NURBANA_KEY_DOWN_ARROW		98
#define	NURBANA_KEY_PG_UP		33
#define	NURBANA_KEY_PG_DOWN		54
#define	NURBANA_KEY_END			53
#define	NURBANA_KEY_PRINT_SCREEN	14
#define	NURBANA_KEY_INSERT		31
#define	NURBANA_KEY_NUMLOCK		0
#define	NURBANA_KEY_NUMPAD_ENTER	91
#define	NURBANA_KEY_NUMPAD_7		55
#define	NURBANA_KEY_NUMPAD_4		72
#define	NURBANA_KEY_NUMPAD_8		56
#define	NURBANA_KEY_NUMPAD_6		74
#define	NURBANA_KEY_NUMPAD_2		89
#define	NURBANA_KEY_NUMPAD_9		57
#define	NURBANA_KEY_NUMPAD_3		90
#define	NURBANA_KEY_NUMPAD_1		88
#define	NURBANA_KEY_NUMPAD_5		73
#define	NURBANA_KEY_NUMPAD_0		100
#define	NURBANA_KEY_NUMPAD_PERIOD	101
#define	NURBANA_KEY_NUMPAD_ASTERISK	36
#define	NURBANA_KEY_NUMPAD_PLUS		58
#define	NURBANA_KEY_NUMPAD_MINUS	37
#define	NURBANA_KEY_NUMPAD_SLASH	35
#define	NURBANA_KEY_F1			2
#define	NURBANA_KEY_F2			3
#define	NURBANA_KEY_F3			4
#define	NURBANA_KEY_F4			5
#define	NURBANA_KEY_F5			6
#define	NURBANA_KEY_F6			7
#define	NURBANA_KEY_F7			8
#define	NURBANA_KEY_F8			9
#define	NURBANA_KEY_F9			10
#define	NURBANA_KEY_F10			11
#define	NURBANA_KEY_F11			12
#define	NURBANA_KEY_F12			13
#define	NURBANA_KEY_SHIFT_LEFT		221
#define	NURBANA_KEY_SHIFT_RIGHT		221
#define	NURBANA_KEY_CTRL_LEFT		222
#define	NURBANA_KEY_CTRL_RIGHT		224
#define	NURBANA_KEY_CAPS_LOCK		0
#define	NURBANA_KEY_ALT_LEFT		0
#define	NURBANA_KEY_ALT_RIGHT		0
#define	NURBANA_KEY_DELETE		52
#define	NURBANA_KEY_SPACEBAR		94
